### ISSUE TITLE
チーム情報の操作は、チームのリーダーしかできないようにすること

### ISSUE THREAD

**Issue by o-t-k-t** [o-t-k-t/team_dev_exercise#3]
現状では、

そのTeamに所属しているUserの削除（離脱）が、どのUserでもできる
TeamのeditをTeamのリーダー（オーナー）以外でも自由にできる
どのUserでも自由にチームメンバー招待ができる
という仕様になっているが、これを、

Teamに所属しているUserの削除（離脱）は、そのTeamのオーナーか、そのUser自身しかできないようにすること
TeamのeditはTeamのリーダー（オーナー）のみができるようにすること
という仕様に変更すること

また、その他、アプリケーションの挙動に不審な点やエラーがないこと。

その他、質問や確認事項などがあれば別途課題投稿欄のコメントで質問すること

今回テストは不要

**Comment by shibatadaiki** [comment]
基本の処理はOKそうです！
あとは任意のタイミングでマージしてください！

**Comment by shibatadaiki** [comment]
destroyアクションのリファクタなども、余裕があればやってみてください！
